### ISSUE TITLE
Problem with names containing colon

### ISSUE THREAD

**Issue by hamidi2** [doublecmd/plugins#14]
Hi Christian,
Thank you for the plugin. It was required for DC as it was for TC. We're still waiting for the same TC for Linux. You changed the name from WC to TC for this purpose. You remember?
Anyway, I experienced a problem with the plugin when packing a name containing colon. It locates at the root when opening the lst file with DC. As well, what you see is the remainder of the name (the portion after colon). For example if you have:
a/b:c.obj
you'll get:
/c.obj

**Comment by hamidi2** [comment]
Oh sorry, I thought it's dedicated to diskdir plugin from Christian Ghisler. I hope he'll see my comment.

**Comment by alexx2000** [comment]
It's ported to Linux by me. Fixed.

**Comment by hamidi2** [comment]
Thanks :)
