### ISSUE TITLE
I Found some code for PDF Preview, but DC Crash

### ISSUE THREAD

**Issue by malliwi88** [doublecmd/plugins#4]
Hi anyone...

I found [this repo](https://github.com/bodqhrohro/DCPoppler), with some code for generating a PDF preview plugin for DC.

I just compile it with:
```bash
make
```
## Dependences are: (ubuntu machine)
```bash
sudo apt-get install build-essential libgtk2.0-dev libpoppler-glib-dev
```
any direction or attention to it, It's apreciated.

Because it's an important feature for a file manager on linux, specially for GNOME and XFCE desktops.

**Comment by alexx2000** [comment]
https://github.com/j2969719/doublecmd-plugins/tree/master/plugins/wlx/wlxpview
